### ISSUE TITLE
Mayor page link to candidate website incorrect

### ISSUE THREAD

**Issue by nancyheiss** [opensandiego/sdvv-frontend#100]
On the Mayor page there is a link that looks like it goes to the candidate's web site but it does not:

```<div _ngcontent-uji-c9="" class="website-link"><mat-icon _ngcontent-uji-c9="" class="mat-icon notranslate material-icons mat-icon-no-color" role="img" aria-hidden="true">link</mat-icon><a _ngcontent-uji-c9="" href="">Website</a></div>```

Testing Env: Chrome Version 84.0.4147.89 (Official Build) (64-bit) on Mac OS 10.15.6 (19G73)

**Comment by robertgz** [comment]
Fixes #100
