### ISSUE TITLE
Mayor page Industry Breakdown table issues

### ISSUE THREAD

**Issue by nancyheiss** [opensandiego/sdvv-frontend#102]
On the Mayor page, the By Industry table needs more spacing, but it is not clear what this is so it may also need some re-design or at least a good explanation in the ToolTip.

1. It is not clear what the left column with the green dots represents. Why green dots and how are those different job titles related to the contributions for this candidate? <del>Maybe need a table header row to describe each column?</del>
2. <del>Need more padding between the columns.</del
3. <del>Right justify the column with the dollar amounts, and can we eliminate the decimal/cents (looks like all amounts are whole dollars anyway).</del>
4. <del>The percentages look off. Are these values accurate? What do they represent?</del>

Testing Env: Chrome Version 84.0.4147.89 (Official Build) (64-bit) on Mac OS 10.15.6 (19G73)

**Comment by tommy-stone** [comment]
Issue #2 was fixed in a previous request by Dom.

**Comment by domdreams** [comment]
I know the dots don't provide a lot of value now to the design but the colors are going to coordinate with the full details bar chart we will be making in phase 2. I think if we can just leave them there for aesthetics this phase they will make more sense on phase 2. @tommy-stone @nancyheiss

**Comment by robertgz** [comment]
Marking this as closed since the concerns in item 1 have been addressed in the comments.
