### ISSUE TITLE
Mayor detail page Raised / Donors spacing issue

### ISSUE THREAD

**Issue by nancyheiss** [opensandiego/sdvv-frontend#103]
On the mayor page in the candidate detail there needs to be some more padding between Raised / Donors:

```<div _ngcontent-uji-c9="" class="raised-donors p-grid p-justify-center p-align-center p-col-12 p-xl-3 p-lg-3"><div _ngcontent-uji-c9="" class="raised p-col-6 p-xl-3 p-lg-3 p-md-3"><p _ngcontent-uji-c9="" class="raised-title">Raised</p><div _ngcontent-uji-c9="" class="raised-amount">$150,000</div></div><div _ngcontent-uji-c9="" class="donors p-col-6 p-xl-3 p-lg-3 p-md-3"><p _ngcontent-uji-c9="" class="donors-title">Donors</p><div _ngcontent-uji-c9="" class="donors-amount">3250</div></div></div>```

Please see screenshot:
<img width="144" alt="Screen Shot 2020-09-08 at 9 14 43 PM" src="https://user-images.githubusercontent.com/6857695/92553643-56588480-f218-11ea-81ca-4ba2921ca260.png">

Testing Env: Chrome Version 84.0.4147.89 (Official Build) (64-bit) on Mac OS 10.15.6 (19G73)

**Comment by aidan-plenert-macdonald** [comment]
What browser? I'm not seeing this on Chrome nor Firefox on Linux. Can someone reproduce this error?

**Comment by robertgz** [comment]
I see the issue when the browser width is greater than about 990 px.

Tested on Chrome Version 85.0.4183.121 (Official Build) (64-bit) and Firefox 81.0 (64-bit) on Windows 10.

**Comment by domdreams** [comment]
![Uploading raise.png…]()

**Comment by domdreams** [comment]
![Screen Shot 2020-10-12 at 10 51 02 AM](https://user-images.githubusercontent.com/12375144/95776277-d9865380-0c78-11eb-84f0-c7b8498bbd02.png)
@aidan-plenert-macdonald
