### ISSUE TITLE
Mayor detail page Support / Oppose is confusing

### ISSUE THREAD

**Issue by nancyheiss** [opensandiego/sdvv-frontend#104]
On the Mayor detail page there is a an issue with the Support / Oppose. Currently, for Barbara Bry it shows $153.675K for support. I think that showing the value in thousands in this way is confusing. People are not used to seeing 3 digits after a decimal point for dollar amounts. Better to not force the user to do math in their head. I can't tell if the same thing is done for the oppose value since it is currently 0.

Please see screenshot:
<img width="407" alt="Screen Shot 2020-09-08 at 9 20 03 PM" src="https://user-images.githubusercontent.com/6857695/92553951-1ba31c00-f219-11ea-9fe6-d98622d6042f.png">

Testing Env: Chrome Version 84.0.4147.89 (Official Build) (64-bit) on Mac OS 10.15.6 (19G73)

**Comment by nancyheiss** [comment]
Will leave this as is for now in case there will be some money in opposition for some candidates by the time of the election.

**Comment by nancyheiss** [comment]
For the Support amount, remove the 'K' and use normal formatting. If over 1 million, round to 4 digits and add 'M' at the end.

**Comment by aidan-plenert-macdonald** [comment]
https://github.com/opensandiego/sdvv-frontend/pull/118 Has the fix
