### ISSUE TITLE
Mayor candidate tile needs extra padding for current job title

### ISSUE THREAD

**Issue by nancyheiss** [opensandiego/sdvv-frontend#105]
The mayoral candidate tile (and probably all candidate tiles) needs a little extra padding on the line that shows the candidates current job/role. Please see screenshot:

<img width="200" alt="Screen Shot 2020-09-08 at 9 30 42 PM" src="https://user-images.githubusercontent.com/6857695/92554674-c1a35600-f21a-11ea-88fa-7888edebe22b.png">

Testing Env: Chrome Version 84.0.4147.89 (Official Build) (64-bit) on Mac OS 10.15.6 (19G73)

**Comment by tommy-stone** [comment]
Tested and confirmed adding space between / allows for candidate card to display title properly. Updated candidate csv file and linking to PR #124
