### ISSUE TITLE
Last Updated shows invalid date

### ISSUE THREAD

**Issue by nancyheiss** [opensandiego/sdvv-frontend#108]
The 'Last Updated' in the footer shows an invalid date:

```<p class="updated">Last Updated 00/00/0000</p>```

Screenshot:
<img width="174" alt="Screen Shot 2020-09-08 at 9 39 37 PM" src="https://user-images.githubusercontent.com/6857695/92555132-d3d1c400-f21b-11ea-944b-2fe8c14b3c9f.png">

Testing Env: Chrome Version 84.0.4147.89 (Official Build) (64-bit) on Mac OS 10.15.6 (19G73)

**Comment by robertgz** [comment]
This should have two parts.

1. Script that is run by driver script that updates "last update" in src\assets\candidates\2020\campaign_race_totals.json

2. Front end code that reads "last update" in src\assets\candidates\2020\campaign_race_totals.json
and updates the page.

I am not sure if it has been decided how to represent the date in the json file.

**Comment by robertgz** [comment]
The date is in `campaign_race_totals.json` on the dev branch. The front end code needs to be implemented to read the date.

**Comment by tommy-stone** [comment]
Issue created to link frontend code to json file. New issue is #160 

Closing this issue.
