### ISSUE TITLE
Create in vs out calculation for Mayor

### ISSUE THREAD

**Issue by tommy-stone** [opensandiego/sdvv-frontend#121]
Calculate the in vs out calculations for Mayor candidates found on https://github.com/opensandiego/sdvv-backend/blob/master/candidate_calc_description.md

In vs Out - Mayor calculation - data taken from netfile_api_2020.csv, netfile_api_2019.csv, netfile_api_2018.csv  and sd_zipcodes.csv

**Comment by robertgz** [comment]
Fixed in #137
