### ISSUE TITLE
Improve donut graph transitions between candidates

### ISSUE THREAD

**Issue by robertgz** [opensandiego/sdvv-frontend#142]
When the _In v. Out District_ donut graph on the expanded card is showing and the candidate selection changes the donut redraws rather then transitioning between the old amounts and the new amounts.

The _Raised v. Spent_ bar graph and the _Opposed vs. Support_ bar do have smooth transitions between candidate selections. The donut graph should also have a smooth transition.

**Comment by aidan-plenert-macdonald** [comment]
I don't see this behavior of the `dev` branch. I see it do a smooth transition. The pie chart will kind of spin the lines to the correct spots

**Comment by robertgz** [comment]
Thanks for checking. Are you seeing it transition in a similar way to the gif below? 
This was from  https://bl.ocks.org/mbostock/1346410

![2020-10-04_14-59-30](https://user-images.githubusercontent.com/1051611/95028046-3fa82080-0652-11eb-9fa4-f7e4160a5f9a.gif)

**Comment by aidan-plenert-macdonald** [comment]
Yeah, Looks just like that.

**Comment by robertgz** [comment]
Thanks, it must an operating system related issue. I am seeing it as below in different browsers on Windows 10.
![2020-10-04_15-45-30](https://user-images.githubusercontent.com/1051611/95028935-15a62c80-0659-11eb-864a-636c365d9615.gif)
