### ISSUE TITLE
Remove "full details" link in candidate cards

### ISSUE THREAD

**Issue by tommy-stone** [opensandiego/sdvv-frontend#157]
Phase 2 will contain the full details page. Currently links go directly to a construction page. Removing until full detail page is ready from phase 2. 

![image](https://user-images.githubusercontent.com/16555335/95694055-adb98e00-0be4-11eb-804d-06c8653cba19.png)

**Comment by pineappleslush** [comment]
Here's a PR for this issue: #211

**Comment by robertgz** [comment]
@domdreams I think the labels are not setup to do anything other than provide information to us. This issue should be closed if it is no longer an issue. It can be re-opened later if needed. @tommy-stone
