### ISSUE TITLE
Update mayor, city council and city attorney sums to read from src/assets/candidates/2020/campaign_race_totals.json

### ISSUE THREAD

**Issue by tommy-stone** [opensandiego/sdvv-frontend#159]
Currently the splash page contains the Mayor, City Attorney and City Council sums. Link these numbers to the numbers found in the json file at src/assets/candidates/2020/campaign_race_totals.json

![image](https://user-images.githubusercontent.com/16555335/95700898-fb41f500-0bfc-11eb-8352-53a66d24c885.png)

**Sample data from json found as of 10/04**
{
  "mayor": "4199119",
  "city council": "4924600",
  "city attorney": "4199119",
  "last update": "10/04/2020"
}

**Comment by matthew9510** [comment]
Resource used to import JSON file:
https://hackernoon.com/import-json-into-typescript-8d465beded79
