### ISSUE TITLE
Update "last updated" so it pulls information from src/assets/candidates/2020/campaign_race_totals.json

### ISSUE THREAD

**Issue by tommy-stone** [opensandiego/sdvv-frontend#160]
![image](https://user-images.githubusercontent.com/16555335/95701112-8fac5780-0bfd-11eb-9e66-eef3244fc4ae.png)

src/assets/candidates/2020/campaign_race_totals.json example data

{
  "mayor": "4199119",
  "city council": "4924600",
  "city attorney": "4199119",
  "last update": "10/04/2020"
}

**Comment by aidan-plenert-macdonald** [comment]
Can this be changed to add the data into https://github.com/opensandiego/sdvv-frontend/pull/177/files#diff-dd2b65c8e999d6559558fc68b5bef0cc91d8382f4942bfdd3c11631e0c6b8d53 ?

**Comment by matthew9510** [comment]
move campaign_race_totals.json in to candidates.json

**Comment by matthew9510** [comment]
Pulling the data from campaign_race_totals.json into the splash and home component.

**Comment by matthew9510** [comment]
Resource used to import JSON file: 
https://hackernoon.com/import-json-into-typescript-8d465beded79
