### ISSUE TITLE
Calculation - Number of candidates in each race

### ISSUE THREAD

**Issue by tommy-stone** [opensandiego/sdvv-frontend#162]
use the google drive spreadsheet https://docs.google.com/spreadsheets/d/1mENueYg0PhXE_MA9AypWWBJvBLdY03b8H_N_aIW-Ohw/edit#gid=0 and find all unique offices in the "Office" column. From this find the total number of candidates from each office.

Output the data into a json format with "office name" and a string with the total number of candidates running for that office.

Example
{
    "mayor": "10",
    "city attorney": "12"
}

This file will be located at src/assets/candidates/2020/campaign_candidate_totals.json

**Comment by robertgz** [comment]
It looks like number_of_candidates_calculation.py needs to be added to driver_script.

**Comment by robertgz** [comment]
This task has been completed.
