### ISSUE TITLE
Swap out duplicate code and hardcoding of district names for loops

### ISSUE THREAD

**Issue by aidan-plenert-macdonald** [opensandiego/sdvv-frontend#183]
Some of the district names are hard coded. For example, https://github.com/opensandiego/sdvv-frontend/blob/dev/src/app/components/home/home.component.html#L62

Similar to https://github.com/opensandiego/sdvv-frontend/pull/177/files#diff-874b7898906b495d0899d9fd3802261a27dbf9fefe5f698dba13d24d163fd2c8, remove the duplicate code and various hardcoded values in favor of looping through the data

**Comment by ShrimpMantis** [comment]
working on it.

**Comment by ShrimpMantis** [comment]
ready to push my changes
