### ISSUE TITLE
Enable sidenav highlight when candidate selected

### ISSUE THREAD

**Issue by tommy-stone** [opensandiego/sdvv-frontend#195]
Currently when candidate is selected sidenav does not highlight candidate name. 

![image](https://user-images.githubusercontent.com/16555335/97475935-14d88180-190b-11eb-84db-b36a814beedb.png)

**Comment by ShrimpMantis** [comment]
could you make the changes once I check in my changes? I have made some changes in the homecomponent.html file

**Comment by gSoD17** [comment]
That sounds good, I can pull in your changes into my branch once you have it checked in.
