### ISSUE TITLE
When a page is refreshed, the correct candidate is not highlighted in the side nav

### ISSUE THREAD

**Issue by ShrimpMantis** [opensandiego/sdvv-frontend#207]
When a page is refreshed, Eg: - when we are on the mayor page and we press the refresh button in the browser, the page reloads properly but the correct side nav item is not highlighted. The expectation in this case is that mayor side nav item should be highlighted.

![image](https://user-images.githubusercontent.com/20343877/98779289-7cc9a600-23a8-11eb-8e47-5494fcc3560b.png)

**Comment by pineappleslush** [comment]
Here's a PR for this issue: #210
