### ISSUE TITLE
'All Races' toggle 

### ISSUE THREAD

**Issue by nancyheiss** [opensandiego/sdvv-frontend#28]
The 'All Races' toggle in the upper right hand corner is a little confusing. It's not really clear on first glance what this button is for. I noticed that the left hand filters disappear/reappear after clicking it a few times, but it does not seem to change the content of the main area of the page. 
If this button is just to toggle the filter list, it seems like it should have a different label (wording) and maybe placement closer to the list itself? 
If it is supposed to change what gets displayed, it looks like it's not working as intended.
It also does not change appearance on mouseover the way other buttons do. Is this intentional?

**Comment by domdreams** [comment]
I agree @nancyheiss. I am going to change this to just be a hamburger icon on mobile, I just haven't gotten the chance to do that yet.

**Comment by domdreams** [comment]
@nancyheiss I linked the pull request with these changes.
