### ISSUE TITLE
inconsistent spelling of Voters Voice Initiative

### ISSUE THREAD

**Issue by nancyheiss** [opensandiego/sdvv-frontend#30]
Which way is correct? 

Voter's Voice Initiative
Voters’ Voice Initiatives

Note the placement of the apostrophe and the singular vs. plural on Initiative(s)

**Comment by domdreams** [comment]
Good catch @nancyheiss! Voters’ Voice Initiatives is the correct one. Should be fixed in the latest pull request.

**Comment by nancyheiss** [comment]
Fix verified in https://github.com/opensandiego/sdvv-frontend/pull/34
