### ISSUE TITLE
add links to sources

### ISSUE THREAD

**Issue by nancyheiss** [opensandiego/sdvv-frontend#31]
Can we add some links to the souces here:

The San Diego Campaign Finance Dashboard is being developed by volunteers in a non-partisan coalition as a service to our community. Data has been gathered from public records posted by the **City of San Diego Clerk’s Office** and the **County of San Diego Registrar of Voters Public Portal** in order to create the graphs and summaries for each candidate’s campaign.

**Comment by nancyheiss** [comment]
@domdreams I'm looking at your fix and I don't see the part about the County of San Diego Registrar of Voters Public Portal... it almost looks like the text got truncated...

> The San Diego Campaign Finance Dashboard is being developed by volunteers in a non-partisan coalition as a service to our community. Data has been gathered from public records posted by the City of San Diego Clerk’s Office in order to create the graphs and summaries for each candidate’s campaign.

**Comment by domdreams** [comment]
Hey @nancyheiss I removed that because from our previous discussions it sounded like we don't actually use the county as a source for data.

**Comment by nancyheiss** [comment]
> Hey @nancyheiss I removed that because from our previous discussions it sounded like we don't actually use the county as a source for data.

@domdreams I thought that some was from the county and some was from the city, but I don't really know. @tommy-stone can you confirm? Thanks!
