### ISSUE TITLE
Download 2018 data for from netfile API

### ISSUE THREAD

**Issue by tommy-stone** [opensandiego/sdvv-frontend#78]
Candidate data also goes back to 2018. Download data from netfile API, name file netfile_api_2019.csv and save to src/assests/data

**Comment by robertgz** [comment]
Should the 2018 data be in the same file with the 2019 data? Or should the 2018 data be in its own file be named netfile_api_2018.csv?

**Comment by tommy-stone** [comment]
The 2018 data should have it's own file called netfile_api_2018.csv and will be in the same folder as the 2019 and 2020 data.

I've created a separate issue to include the netfile_api_2018.csv into the calculations.

**Comment by tommy-stone** [comment]
Closing open issue as item is complete
