### ISSUE TITLE
Candidate card numbers are not updating when switching between candidates

### ISSUE THREAD

**Issue by tommy-stone** [opensandiego/sdvv-frontend#90]
Clicking on Mayor panel > then clicking on the candidates detail card will show the candidate card. If you switch from one candidate card to the other the below calculations are not updated.

- raised vs spent money and bar charts
- By industry top 5 do not change
- The oppose vs support numbers do not change

**Comment by robertgz** [comment]
This appear to be fixed. Closing issue.
