### ISSUE TITLE
Create an "average donation" calculation.

### ISSUE THREAD

**Issue by tommy-stone** [opensandiego/sdvv-frontend#95]
* Average Donation 
  1. Download the candidate's from the following file (https://docs.google.com/spreadsheets/d/1mENueYg0PhXE_MA9AypWWBJvBLdY03b8H_N_aIW-Ohw/edit#gid=0)
  2. Create a for loop to run through the Candidate_Name column
  3. Filter by the candidate's name
  4. Sum the total for each contribution in the Trans_Amt1 column and divide by the number of contributions
  5. Round this number by dollar unit (44.30 will be 44) 
  6. Update the average donation key in the candidate's json file (example src/assests/candidates/2020/mayor/barbara_bry/barbara_bry.json)

**Comment by robertgz** [comment]
Fixed by #116.
