### ISSUE TITLE
mis-wording on FAQ page?

### ISSUE THREAD

**Issue by nancyheiss** [opensandiego/sdvv-frontend#97]
Current wording:
What is an independent expenditure?
Independent expenditures are campaign communications that expressly advocate for the election or defeat of a candidate that is not made in cooperation, consultation or concert with; or at the request or suggestion of a candidate, candidate's authorized committee or political party.

Shouldn't this be:  Independent expenditures are campaign **contributions** instead of **communications**?

**Comment by domdreams** [comment]
@nancyheiss We may want to consult with Amy but I believe it is something like "campaign contributions for communications"

**Comment by tommy-stone** [comment]
Potentially solved with a previous merge. @nancyheiss will confirm if changes are correct

**Comment by nancyheiss** [comment]
I don't think this is fixed. @domdreams do we need to check with Amy about the proper wording? Here is what I am seeing right now.
<img width="395" alt="Screen Shot 2020-10-06 at 9 13 02 PM" src="https://user-images.githubusercontent.com/6857695/95286662-d0305d80-0818-11eb-81b8-634e8d2e6c0c.png">

**Comment by domdreams** [comment]
@tommy-stone Looks like @nancyheiss is right I will update to say "campaign contributions for communications"
