### ISSUE TITLE
ToolTips on Mayor page need text

### ISSUE THREAD

**Issue by nancyheiss** [opensandiego/sdvv-frontend#98]
The ToolTips on the Mayor page need text:

<i _ngcontent-xkp-c8="" aria-hidden="true" class="helper-tip fa fa-question-circle" mattooltip="Description goes here." aria-describedby="cdk-describedby-message-0" cdk-describedby-host=""></i>

There are 4 ToolTips in total: 
1. Raised v. Spent 
2. By Industry 
3. In v. Out District 
4. Outside Money 

Testing Env: Chrome Version 84.0.4147.89 (Official Build) (64-bit) on Mac OS 10.15.6 (19G73)

**Comment by nancyheiss** [comment]
@tommy-stone Please provide text for the ToolTips and re-assign to @robertgz

**Comment by domdreams** [comment]
https://docs.google.com/document/d/1ij-0Z0fAaUcy9EFEk9zItaDrL6OcZrhyMFAatX-T9Ew/edit?usp=sharing

@tommy-stone @robertgz @nancyheiss

**Comment by domdreams** [comment]
### Mayor Detail Overview
**Raised v. Spent**
Total campaign funds raised and spent by the candidate.
**Donors by Group**
Total contributions from five largest groups of campaign donors
**In v Out City**
Total campaign funds raised in the city of San Diego versus funds raised outside of city limits.
**Outside Money**
Amount of money raised by independent expenditure committees spent on initiatives in support or opposition of a candidate but not contributing directly to their campaign.

**Comment by nancyheiss** [comment]
@domdreams just 1 suggestion:
Total contributions from five **_the_** largest groups of campaign donors
