### ISSUE TITLE
Chart on Mayor page not displaying properly

### ISSUE THREAD

**Issue by nancyheiss** [opensandiego/sdvv-frontend#99]
The chart on the Mayor page is not displaying properly:

```<canvas _ngcontent-xkp-c8="" basechart="" height="520" width="556" class="chartjs-render-monitor" style="display: block; height: 260px; width: 278px;"></canvas>```

Testing Env: Chrome Version 84.0.4147.89 (Official Build) (64-bit) on Mac OS 10.15.6 (19G73)

Please see screenshot
<img width="155" alt="Screen Shot 2020-09-08 at 8 45 20 PM" src="https://user-images.githubusercontent.com/6857695/92551932-42128880-f214-11ea-8136-085462fcc868.png">

**Comment by aidan-plenert-macdonald** [comment]
https://github.com/opensandiego/sdvv-frontend/pull/119  Fixes this
